# docker-compose.base.yml
services:
  postgres:
    image: pgvector/pgvector:pg17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: webhook_db
    ports:
      - "5433:5432"
    volumes:
      - wa_llm_postgres:/var/lib/postgresql/data
    command: ["postgres", "-c", "log_statement=all"]
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d webhook_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  web-server:
    build: .
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env
      - ./migrations:/app/migrations
    ports:
      - "8000:5001"
    restart: always
    depends_on:
      - postgres
    environment:
      - DB_URI=postgresql+asyncpg://user:password@postgres:5432/postgres
      - OPENAI_API_KEY=${OPENAI_API_KEY}

volumes:
  wa_llm_postgres:
    name: wa_llm_postgres
